# Nixpacks 配置（项目根目录）

[phases.setup]
nixPkgs = ["nodejs_20"]

[start]
cmd = "cd server && npx -y pnpm@8.15.9 prisma db push --accept-data-loss --schema=./prisma/schema.postgres.prisma && node dist/server.js"
